### ISSUE TITLE
Great app but small request

### ISSUE THREAD

**Issue by Martyn29** [noahp/fbapp-TimeDateWeather#1]
Hi

Great clock face. Small request. Could we have the temp in centre grade as an option. I'm from the UK

**Comment by noahp** [comment]
You got it! submitted the update (v0.0.3) for review. Thanks for the suggestion!

**Comment by Martyn29** [comment]
Wow great thanksOn 21 May 2018 13:27, Noah Pendleton <notifications@github.com> wrote:You got it! submitted the update (v0.0.3) for review. Thanks for the suggestion!

**Comment by noahp** [comment]
No worries! once you update, if you view "My Clock" in the app, you should see a little configuration gear that has the settings. You may need to exit the app gallery on the mobile phone and go back it for it to refresh.
![screenshot_20180522-144241](https://user-images.githubusercontent.com/2538614/40383442-ec1cb300-5dce-11e8-9a04-9c23d4fc1c82.png)
![screenshot_20180522-144259](https://user-images.githubusercontent.com/2538614/40383449-efca7afa-5dce-11e8-993c-d4d6dd25c730.png)

**Comment by Martyn29** [comment]
Okay me being a thick man. I have sorted it. What a great clock face.
