### ISSUE TITLE
Date and Time Cut Off 

### ISSUE THREAD

**Issue by snoopyh77** [noahp/fbapp-TimeDateWeather#10]
![A32C2511-41E8-49A2-B5D6-03CDAB3279BB](https://user-images.githubusercontent.com/55512296/72480559-c87de400-37c5-11ea-84e2-c618ec7e97e7.jpeg)

**Comment by snoopyh77** [comment]
Any idea when this will be resolved?

**Comment by noahp** [comment]
Apologies! reproduced, fix on the way. Thank you for reporting!

**Comment by noahp** [comment]
Submitted fix. It might take a few days to be approved and available in the gallery, in the meantime you can use this link (open with your phone) to access the build:
https://gallery.fitbit.com/details/9441c0d4-3370-4295-9df7-c4e1edad8ade

**Comment by noahp** [comment]
Let me know if that link doesn't work, and I can make a one-off link with the fix 👍

**Comment by snoopyh77** [comment]
Thank you!
