### ISSUE TITLE
Weather shows unknown

### ISSUE THREAD

**Issue by ntrouble7** [noahp/fbapp-TimeDateWeather#15]
Noah, I have tried alot of the tips given on other weather related issues with no luck. The weather API shows <default> in settings. I have restarted both phone and Fitbit and tried shutting off WiFi, nothing. I really like this clock app because of the weather feature.

**Comment by noahp** [comment]
Hmm, couple of other things to try:
- verify location permission is enabled for the fitbit app on your phone (it's used by the clockface to get location for weather)
- try requesting weather from the OWM api, see if it's working for your location:
access this URL https://api.openweathermap.org/data/2.5/forecast?appid=76fa7dd2f60e6e7eb5421f1512b9dbc3&lat=LATITUDE&lon=LONGITUDE , but replace the `LATITUDE` and `LONGITUDE` with your current location (you can find that for example by going to google maps and dropping a pin, and grab it from the url, eg for London:
![image](https://user-images.githubusercontent.com/2538614/81501865-92023280-92a8-11ea-97c6-cb404da9f884.png)
). Example for London: http://api.openweathermap.org/data/2.5/forecast?appid=76fa7dd2f60e6e7eb5421f1512b9dbc3&lat=51.5287718&lon=-0.2416802
If it's working, you should see it spit out a bunch of JSON text. Ideally testing the URL from the same phone you use with your Fitbit device.

If the OWM api doesn't work for your location, if you want to post the error here I can try to diagnose what's going on!

**Comment by nertz56** [comment]
My versa does the same thing if I replace the default OWM key with my own. Only way to fix is to remove the watch face and reinstall to default back to original settings.  

Excellent watch face though, I like the clean look and easy readability of any element on the face.  5 stars when you fix the OWM key issue.

**Comment by noahp** [comment]
Hmm, let me test non-default keys, I'll update here when I have something.

**Comment by ntrouble7** [comment]
Still having the same issues with the clock face. I just received a brand new ionic on 7/21/20 and the weather is not working on any of the 3rd party clock faces.

**Comment by noahp** [comment]
Hmm, I'd guess something on the network configuration on the companion phone or network it's connected to :confused: . I'd check firewall/VPN or DNS settings perhaps?

**Comment by ntrouble7** [comment]
It's all good, I purchased a clock face.Thanks for the help.

Sent from Yahoo Mail on Android 
 
  On Tue, Jul 28, 2020 at 7:23 PM, Noah Pendleton<notifications@github.com> wrote:   


Hmm, I'd guess something on the network configuration on the companion phone or network it's connected to 😕 . I'd check firewall/VPN or DNS settings perhaps?

**Comment by noahp** [comment]
FYI there was a bug in the way the non-default OWM key was loaded from settings :( fixed in 6c80fa5 and published as version 0.1.2 to the gallery.
